// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'6f120827ecee607ce78d95b8a20fc4b1c17376498160a368956e3c7a76b672d2'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Chapter: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
      readonly chapterName: CodecTypes['pg/text@1']['output'];
      readonly isPublished: CodecTypes['pg/bool@1']['output'];
      readonly order: CodecTypes['pg/int4@1']['output'];
      readonly createdDate: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Comment: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly commentorId: CodecTypes['pg/int4@1']['output'];
      readonly paragraphId: CodecTypes['pg/int4@1']['output'];
      readonly commentText: CodecTypes['pg/text@1']['output'];
      readonly commentedDate: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Library: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly readerId: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
      readonly isArchived: CodecTypes['pg/bool@1']['output'];
    };
    readonly Paragraph: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly chapterId: CodecTypes['pg/int4@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
    };
    readonly ReadingListName: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly readerId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Review: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly readerId: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
      readonly reviewText: CodecTypes['pg/text@1']['output'];
    };
    readonly StoriesInReadingList: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly readingListNameId: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Story: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly authorId: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly coverPhotoUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly status: 'ONGOING' | 'COMPLETED';
    };
    readonly Tag: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly tagName: CodecTypes['pg/text@1']['output'];
    };
    readonly TagStoryRelation: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly tagId: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Vote: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly voterId: CodecTypes['pg/int4@1']['output'];
      readonly chapterId: CodecTypes['pg/int4@1']['output'];
      readonly votedTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Chapter: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
      readonly chapterName: CodecTypes['pg/text@1']['input'];
      readonly isPublished: CodecTypes['pg/bool@1']['input'];
      readonly order: CodecTypes['pg/int4@1']['input'];
      readonly createdDate: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Comment: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly commentorId: CodecTypes['pg/int4@1']['input'];
      readonly paragraphId: CodecTypes['pg/int4@1']['input'];
      readonly commentText: CodecTypes['pg/text@1']['input'];
      readonly commentedDate: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Library: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly readerId: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
      readonly isArchived: CodecTypes['pg/bool@1']['input'];
    };
    readonly Paragraph: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly chapterId: CodecTypes['pg/int4@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
    };
    readonly ReadingListName: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly readerId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Review: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly readerId: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
      readonly reviewText: CodecTypes['pg/text@1']['input'];
    };
    readonly StoriesInReadingList: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly readingListNameId: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Story: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly authorId: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly coverPhotoUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly status: 'ONGOING' | 'COMPLETED';
    };
    readonly Tag: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly tagName: CodecTypes['pg/text@1']['input'];
    };
    readonly TagStoryRelation: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly tagId: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Vote: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly voterId: CodecTypes['pg/int4@1']['input'];
      readonly chapterId: CodecTypes['pg/int4@1']['input'];
      readonly votedTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly chapter: {
      readonly chapterName: CodecTypes['pg/text@1']['output'];
      readonly createdDate: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isPublished: CodecTypes['pg/bool@1']['output'];
      readonly order: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
    };
    readonly comment: {
      readonly commentedDate: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly commentorId: CodecTypes['pg/int4@1']['output'];
      readonly commentText: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly paragraphId: CodecTypes['pg/int4@1']['output'];
    };
    readonly library: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isArchived: CodecTypes['pg/bool@1']['output'];
      readonly readerId: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
    };
    readonly paragraph: {
      readonly chapterId: CodecTypes['pg/int4@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
    };
    readonly readingListName: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly readerId: CodecTypes['pg/int4@1']['output'];
    };
    readonly review: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly readerId: CodecTypes['pg/int4@1']['output'];
      readonly reviewText: CodecTypes['pg/text@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
    };
    readonly storiesInReadingList: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly readingListNameId: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
    };
    readonly story: {
      readonly authorId: CodecTypes['pg/int4@1']['output'];
      readonly coverPhotoUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly status: 'ONGOING' | 'COMPLETED';
    };
    readonly tag: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly tagName: CodecTypes['pg/text@1']['output'];
    };
    readonly tagStoryRelation: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly storyId: CodecTypes['pg/int4@1']['output'];
      readonly tagId: CodecTypes['pg/int4@1']['output'];
    };
    readonly user: {
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly vote: {
      readonly chapterId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly votedTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly voterId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly chapter: {
      readonly chapterName: CodecTypes['pg/text@1']['input'];
      readonly createdDate: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isPublished: CodecTypes['pg/bool@1']['input'];
      readonly order: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
    };
    readonly comment: {
      readonly commentedDate: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly commentorId: CodecTypes['pg/int4@1']['input'];
      readonly commentText: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly paragraphId: CodecTypes['pg/int4@1']['input'];
    };
    readonly library: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isArchived: CodecTypes['pg/bool@1']['input'];
      readonly readerId: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
    };
    readonly paragraph: {
      readonly chapterId: CodecTypes['pg/int4@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
    };
    readonly readingListName: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly readerId: CodecTypes['pg/int4@1']['input'];
    };
    readonly review: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly readerId: CodecTypes['pg/int4@1']['input'];
      readonly reviewText: CodecTypes['pg/text@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
    };
    readonly storiesInReadingList: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly readingListNameId: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
    };
    readonly story: {
      readonly authorId: CodecTypes['pg/int4@1']['input'];
      readonly coverPhotoUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly status: 'ONGOING' | 'COMPLETED';
    };
    readonly tag: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly tagName: CodecTypes['pg/text@1']['input'];
    };
    readonly tagStoryRelation: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly storyId: CodecTypes['pg/int4@1']['input'];
      readonly tagId: CodecTypes['pg/int4@1']['input'];
    };
    readonly user: {
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly vote: {
      readonly chapterId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly votedTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly voterId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly chapter: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly storyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly chapterName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isPublished: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdDate: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'chapter_storyId_idx_cd452158';
                  readonly prefix: 'chapter_storyId_idx';
                  readonly columns: readonly ['storyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'chapter';
                    readonly columns: readonly ['storyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'story';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly comment: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly commentorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly paragraphId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly commentText: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly commentedDate: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'comment_commentorId_idx_ba461a76';
                  readonly prefix: 'comment_commentorId_idx';
                  readonly columns: readonly ['commentorId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'comment_paragraphId_idx_2e981790';
                  readonly prefix: 'comment_paragraphId_idx';
                  readonly columns: readonly ['paragraphId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'comment';
                    readonly columns: readonly ['commentorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'comment';
                    readonly columns: readonly ['paragraphId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'paragraph';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly library: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly readerId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly storyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly isArchived: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'library_readerId_idx_a6f61ebe';
                  readonly prefix: 'library_readerId_idx';
                  readonly columns: readonly ['readerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'library_storyId_idx_cd452158';
                  readonly prefix: 'library_storyId_idx';
                  readonly columns: readonly ['storyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'library';
                    readonly columns: readonly ['readerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'library';
                    readonly columns: readonly ['storyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'story';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly paragraph: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly chapterId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'paragraph_chapterId_idx_411dd3d6';
                  readonly prefix: 'paragraph_chapterId_idx';
                  readonly columns: readonly ['chapterId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'paragraph';
                    readonly columns: readonly ['chapterId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'chapter';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly readingListName: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly readerId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'readingListName_readerId_idx_a6f61ebe';
                  readonly prefix: 'readingListName_readerId_idx';
                  readonly columns: readonly ['readerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'readingListName';
                    readonly columns: readonly ['readerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly review: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly readerId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly storyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reviewText: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'review_readerId_idx_a6f61ebe';
                  readonly prefix: 'review_readerId_idx';
                  readonly columns: readonly ['readerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'review_storyId_idx_cd452158';
                  readonly prefix: 'review_storyId_idx';
                  readonly columns: readonly ['storyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'review';
                    readonly columns: readonly ['readerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'review';
                    readonly columns: readonly ['storyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'story';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly storiesInReadingList: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly readingListNameId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly storyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'storiesInReadingList_readingListNameId_idx_c16bacc8';
                  readonly prefix: 'storiesInReadingList_readingListNameId_idx';
                  readonly columns: readonly ['readingListNameId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'storiesInReadingList_storyId_idx_cd452158';
                  readonly prefix: 'storiesInReadingList_storyId_idx';
                  readonly columns: readonly ['storyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'storiesInReadingList';
                    readonly columns: readonly ['readingListNameId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'readingListName';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'storiesInReadingList';
                    readonly columns: readonly ['storyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'story';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly story: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly authorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly coverPhotoUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'story_authorId_idx_e47547ed';
                  readonly prefix: 'story_authorId_idx';
                  readonly columns: readonly ['authorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'story';
                    readonly columns: readonly ['authorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly tag: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly tagName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly tagStoryRelation: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly tagId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly storyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'tagStoryRelation_tagId_idx_86854244';
                  readonly prefix: 'tagStoryRelation_tagId_idx';
                  readonly columns: readonly ['tagId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tagStoryRelation_storyId_idx_cd452158';
                  readonly prefix: 'tagStoryRelation_storyId_idx';
                  readonly columns: readonly ['storyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tagStoryRelation';
                    readonly columns: readonly ['tagId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tag';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tagStoryRelation';
                    readonly columns: readonly ['storyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'story';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly vote: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly voterId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly chapterId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly votedTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'vote_voterId_idx_9733d79c';
                  readonly prefix: 'vote_voterId_idx';
                  readonly columns: readonly ['voterId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'vote_chapterId_idx_411dd3d6';
                  readonly prefix: 'vote_chapterId_idx';
                  readonly columns: readonly ['chapterId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'vote';
                    readonly columns: readonly ['voterId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'vote';
                    readonly columns: readonly ['chapterId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'chapter';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly Status: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ONGOING', 'COMPLETED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly story: { readonly namespace: 'public' & NamespaceId; readonly model: 'Story' };
    readonly chapter: { readonly namespace: 'public' & NamespaceId; readonly model: 'Chapter' };
    readonly paragraph: { readonly namespace: 'public' & NamespaceId; readonly model: 'Paragraph' };
    readonly comment: { readonly namespace: 'public' & NamespaceId; readonly model: 'Comment' };
    readonly vote: { readonly namespace: 'public' & NamespaceId; readonly model: 'Vote' };
    readonly tag: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tag' };
    readonly tagStoryRelation: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TagStoryRelation';
    };
    readonly review: { readonly namespace: 'public' & NamespaceId; readonly model: 'Review' };
    readonly library: { readonly namespace: 'public' & NamespaceId; readonly model: 'Library' };
    readonly readingListName: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ReadingListName';
    };
    readonly storiesInReadingList: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'StoriesInReadingList';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Chapter: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly storyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly chapterName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isPublished: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly order: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly StoryRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Story';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['storyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly paragraphs: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Paragraph';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['chapterId'];
                };
              };
              readonly votes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Vote' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['chapterId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'chapter';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly storyId: { readonly column: 'storyId' };
                readonly chapterName: { readonly column: 'chapterName' };
                readonly isPublished: { readonly column: 'isPublished' };
                readonly order: { readonly column: 'order' };
                readonly createdDate: { readonly column: 'createdDate' };
              };
            };
          };
          readonly Comment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly commentorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly paragraphId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly commentText: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly commentedDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly commentorRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['commentorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly paragraphRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Paragraph';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['paragraphId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'comment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly commentorId: { readonly column: 'commentorId' };
                readonly paragraphId: { readonly column: 'paragraphId' };
                readonly commentText: { readonly column: 'commentText' };
                readonly commentedDate: { readonly column: 'commentedDate' };
              };
            };
          };
          readonly Library: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly readerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly storyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isArchived: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly readerRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['readerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly storyRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Story';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['storyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'library';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly readerId: { readonly column: 'readerId' };
                readonly storyId: { readonly column: 'storyId' };
                readonly isArchived: { readonly column: 'isArchived' };
              };
            };
          };
          readonly Paragraph: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly chapterId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly chapterRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Chapter';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['chapterId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly comments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Comment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['paragraphId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'paragraph';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly chapterId: { readonly column: 'chapterId' };
                readonly content: { readonly column: 'content' };
              };
            };
          };
          readonly ReadingListName: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly readerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly readerRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['readerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly storiesInReadingLists: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'StoriesInReadingList';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['readingListNameId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'readingListName';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly readerId: { readonly column: 'readerId' };
              };
            };
          };
          readonly Review: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly readerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly storyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reviewText: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly readerRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['readerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly storyRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Story';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['storyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'review';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly readerId: { readonly column: 'readerId' };
                readonly storyId: { readonly column: 'storyId' };
                readonly reviewText: { readonly column: 'reviewText' };
              };
            };
          };
          readonly StoriesInReadingList: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly readingListNameId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly storyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly readingListNameRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ReadingListName';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['readingListNameId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly storyRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Story';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['storyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'storiesInReadingList';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly readingListNameId: { readonly column: 'readingListNameId' };
                readonly storyId: { readonly column: 'storyId' };
              };
            };
          };
          readonly Story: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly authorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly coverPhotoUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly UserRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['authorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly chapters: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Chapter';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['storyId'];
                };
              };
              readonly libraries: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Library';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['storyId'];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Review';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['storyId'];
                };
              };
              readonly storiesInReadingLists: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'StoriesInReadingList';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['storyId'];
                };
              };
              readonly tagStoryRelations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'TagStoryRelation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['storyId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'story';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly authorId: { readonly column: 'authorId' };
                readonly name: { readonly column: 'name' };
                readonly coverPhotoUrl: { readonly column: 'coverPhotoUrl' };
                readonly description: { readonly column: 'description' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Tag: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tagName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly tagStoryRelations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'TagStoryRelation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tagId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tag';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tagName: { readonly column: 'tagName' };
              };
            };
          };
          readonly TagStoryRelation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tagId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly storyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly storyRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Story';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['storyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly tagRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tag' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tagId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tagStoryRelation';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tagId: { readonly column: 'tagId' };
                readonly storyId: { readonly column: 'storyId' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly comments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Comment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['commentorId'];
                };
              };
              readonly libraries: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Library';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['readerId'];
                };
              };
              readonly readingListNames: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ReadingListName';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['readerId'];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Review';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['readerId'];
                };
              };
              readonly stories: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Story';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['authorId'];
                };
              };
              readonly votes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Vote' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['voterId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Vote: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly voterId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly chapterId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly votedTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly chapterRelation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Chapter';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['chapterId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly voterRelation: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['voterId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'vote';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly voterId: { readonly column: 'voterId' };
                readonly chapterId: { readonly column: 'chapterId' };
                readonly votedTime: { readonly column: 'votedTime' };
              };
            };
          };
        };
        readonly enum: {
          readonly Status: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ONGOING'; readonly value: 'ONGOING' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
